//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;

namespace Bacchus.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [UserScopedSetting]
        [DefaultSettingValue("800")]
        public int Height {
            get { return (int) this["Height"]; }
            set { this["Height"] = value; } 
        }
        
        [UserScopedSetting]
        [DefaultSettingValue("1200")]
        public int Width {
            get { return (int) this["Width"]; }
            set { this["Width"] = value; } 
        }
        
        [UserScopedSetting]
        [DefaultSettingValue("false")]
        public bool Maximized {
            get { return (bool) this["Maximized"]; }
            set { this["Maximized"] = value; } 
        }
        
        [UserScopedSetting]
        [DefaultSettingValue("false")]
        public bool Minimized {
            get { return (bool) this["Minimized"]; }
            set { this["Minimized"] = value; } 
        }

        [UserScopedSetting]
        [DefaultSettingValue("true")]
        public bool Normal
        {
            get { return (bool) this["Normal"]; }
            set { this["Normal"] = value; }
        }
    }
}
